# Define the Docker image to use
image: golang:latest

# Define the stages of the CI/CD pipeline
stages:
  - test
  - build
  - deploy

# Test stage: Format code, run vetting, and execute tests
test:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

# Build stage: Compile the project and create binaries
build:
  stage: build
  script:
    - mkdir -p binaries
    - go build -o ./binaries ./...

  artifacts:
    paths:
      - binaries/*

# Deploy stage: Install Ruby, RubyGems, and deploy to Heroku
heroku_deploy:
  stage: deploy
  script:
    - apt-get update && apt-get install -y ruby ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_PRODUCTION_KEY
  environment:
    name: production