# Define the Docker image to use
image: golang:latest

# Define the stages of the CI/CD pipeline
stages:
  - test
  - build
  - deploy
  - heroku_deploy

# Test stage: Format code, run vetting, and execute tests
test:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

# Build stage: Compile the project and create binaries
build:
  stage: build
  script:
    - mkdir -p binaries
    - go build -o ./binaries ./...

  artifacts:
    paths:
      - binaries/*

# Deploy stage: Define your deployment script
deploy:
  stage: deploy
  script:
    - echo "Define your deployment script!"
  environment:
    name: production

# Heroku deployment stage: Deploy to Heroku
heroku_deploy:
  stage: heroku_deploy
  script:
    - curl https://cli-assets.heroku.com/install.sh | sh
    - echo "$HEROKU_PRODUCTION_KEY" | /usr/local/bin/heroku login --stdin
    - /usr/local/bin/heroku git:remote -a cs2-parser
    - git push heroku HEAD:main
  environment:
    name: production
